# Generated by Django 3.1.4 on 2021-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210103_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistingpage',
            name='custom_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
