# Generated by Django 3.1.1 on 2020-09-27 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200927_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='theme',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
