# Generated by Django 3.1.1 on 2020-09-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
