# Generated by Django 3.1.1 on 2020-09-27 14:46

from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], max_length=20),
        ),
    ]
