# Generated by Django 3.1.1 on 2020-09-27 14:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200927_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(classname='full title'))]),
        ),
    ]
