# Generated by Django 3.1.1 on 2020-09-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0006_auto_20200927_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='sdkhslkjdh',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
