# Generated by Django 3.1.1 on 2020-09-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('flex', '0009_auto_20200927_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='preview_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
    ]
